project_id = "pqkwuksjdpkgpsovuprp"

[functions.auth-guard]
verify_jwt = false

[functions.support-chat]
verify_jwt = false

[functions.reverse-geocode]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.twilio-token]
verify_jwt = false

[functions.secure-call]
verify_jwt = false

[functions.secure-message]
verify_jwt = false

[functions.report-abuse]
verify_jwt = false