import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useEffect } from "react";
import { toast } from "sonner";

export interface Job {
  id: string;
  job_number: string;
  customer_id: string | null;
  driver_id: string | null;
  service_id: string | null;
  status: string | null;
  pickup_address: string | null;
  pickup_lat: number | null;
  pickup_lng: number | null;
  estimated_price: number | null;
  final_price: number | null;
  eta_minutes: number | null;
  notes: string | null;
  rating: number | null;
  review: string | null;
  created_at: string;
  updated_at: string;
  dispatched_at: string | null;
  accepted_at: string | null;
  started_at: string | null;
  completed_at: string | null;
  cancelled_at: string | null;
  cancellation_reason: string | null;
  services?: {
    id: string;
    name: string;
    icon: string | null;
    base_price: number;
  } | null;
  drivers?: {
    id: string;
    user_id: string;
    vehicle_plate: string | null;
    vehicle_make: string | null;
    vehicle_model: string | null;
  } | null;
  customer?: {
    id: string;
    full_name: string | null;
    phone: string | null;
  } | null;
  driverProfile?: {
    id: string;
    full_name: string | null;
    phone: string | null;
  } | null;
}

// Hook to create a new job (customer)
export function useCreateJob() {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async ({
      serviceId,
      pickupAddress,
      pickupLat,
      pickupLng,
      estimatedPrice,
      etaMinutes,
      notes,
    }: {
      serviceId: string;
      pickupAddress: string;
      pickupLat?: number;
      pickupLng?: number;
      estimatedPrice: number;
      etaMinutes?: number;
      notes?: string;
    }) => {
      if (!user?.id) throw new Error("Not authenticated");

      // Job number is auto-generated by database trigger
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data, error } = await supabase
        .from("jobs")
        .insert({
          customer_id: user.id,
          service_id: serviceId,
          pickup_address: pickupAddress,
          pickup_lat: pickupLat ?? null,
          pickup_lng: pickupLng ?? null,
          estimated_price: estimatedPrice,
          eta_minutes: etaMinutes ?? null,
          notes: notes ?? null,
          status: "pending",
        } as any)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["customer-jobs"] });
      queryClient.invalidateQueries({ queryKey: ["admin-active-jobs"] });
    },
  });
}

// Hook to fetch customer's jobs
export function useCustomerJobs() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ["customer-jobs", user?.id],
    queryFn: async () => {
      if (!user?.id) return [];

      const { data, error } = await supabase
        .from("jobs")
        .select(`
          *,
          services (id, name, icon, base_price)
        `)
        .eq("customer_id", user.id)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data;
    },
    enabled: !!user?.id,
  });
}

// Hook to fetch available jobs for drivers (pending jobs)
export function useAvailableJobs(driverId: string | null) {
  return useQuery({
    queryKey: ["available-jobs", driverId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("jobs")
        .select(`
          *,
          services (id, name, icon, base_price)
        `)
        .eq("status", "pending")
        .is("driver_id", null)
        .order("created_at", { ascending: false })
        .limit(10);

      if (error) throw error;

      // Fetch customer profiles
      if (data && data.length > 0) {
        const customerIds = [...new Set(data.map(j => j.customer_id).filter(Boolean))];
        const { data: profiles } = await supabase
          .from("profiles")
          .select("id, full_name, phone")
          .in("id", customerIds);

        return data.map(job => ({
          ...job,
          customer: profiles?.find(p => p.id === job.customer_id) || null,
        }));
      }

      return data;
    },
    enabled: !!driverId,
    refetchInterval: 10000, // Refresh every 10 seconds
  });
}

// Hook to fetch driver's assigned jobs
export function useDriverJobs(driverId: string | null) {
  return useQuery({
    queryKey: ["driver-jobs", driverId],
    queryFn: async () => {
      if (!driverId) return [];

      const { data, error } = await supabase
        .from("jobs")
        .select(`
          *,
          services (id, name, icon, base_price)
        `)
        .eq("driver_id", driverId)
        .in("status", ["accepted", "dispatched", "arrived", "in_progress"])
        .order("accepted_at", { ascending: false });

      if (error) throw error;

      // Fetch customer profiles
      if (data && data.length > 0) {
        const customerIds = [...new Set(data.map(j => j.customer_id).filter(Boolean))];
        const { data: profiles } = await supabase
          .from("profiles")
          .select("id, full_name, phone")
          .in("id", customerIds);

        return data.map(job => ({
          ...job,
          customer: profiles?.find(p => p.id === job.customer_id) || null,
        }));
      }

      return data;
    },
    enabled: !!driverId,
  });
}

// Hook to accept a job (driver)
export function useAcceptJob() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ jobId, driverId }: { jobId: string; driverId: string }) => {
      const { data, error } = await supabase
        .from("jobs")
        .update({
          driver_id: driverId,
          status: "accepted",
          accepted_at: new Date().toISOString(),
        })
        .eq("id", jobId)
        .eq("status", "pending") // Only accept if still pending
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["available-jobs"] });
      queryClient.invalidateQueries({ queryKey: ["driver-jobs"] });
      queryClient.invalidateQueries({ queryKey: ["admin-active-jobs"] });
      toast.success("Job accepted!");
    },
    onError: () => {
      toast.error("Failed to accept job - it may have been taken by another driver");
    },
  });
}

// Hook to update job status (driver)
export function useUpdateJobStatus() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      jobId,
      status,
      finalPrice,
    }: {
      jobId: string;
      status: "dispatched" | "arrived" | "in_progress" | "completed" | "cancelled";
      finalPrice?: number;
    }) => {
      const updates: Record<string, unknown> = { status };

      if (status === "dispatched") {
        updates.dispatched_at = new Date().toISOString();
      } else if (status === "arrived") {
        // No dedicated timestamp column, just status update
      } else if (status === "in_progress") {
        updates.started_at = new Date().toISOString();
      } else if (status === "completed") {
        updates.completed_at = new Date().toISOString();
        if (finalPrice) updates.final_price = finalPrice;
      } else if (status === "cancelled") {
        updates.cancelled_at = new Date().toISOString();
      }

      const { data, error } = await supabase
        .from("jobs")
        .update(updates)
        .eq("id", jobId)
        .select()
        .single();

      if (error) throw error;

      // Fire WhatsApp notification (function no-ops for non-WhatsApp jobs)
      try {
        await supabase.functions.invoke("whatsapp-notify", {
          body: { job_id: jobId, status },
        });
      } catch (e) {
        console.warn("whatsapp-notify failed (non-fatal)", e);
      }

      return data;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["driver-jobs"] });
      queryClient.invalidateQueries({ queryKey: ["customer-jobs"] });
      queryClient.invalidateQueries({ queryKey: ["admin-active-jobs"] });
      
      if (variables.status === "completed") {
        toast.success("Job completed!");
      }
    },
  });
}

// Hook for realtime job updates (for admin dashboard)
export function useRealtimeJobs() {
  const queryClient = useQueryClient();

  useEffect(() => {
    const channel = supabase
      .channel("jobs-realtime")
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: "jobs",
        },
        () => {
          // Invalidate all job-related queries when any job changes
          queryClient.invalidateQueries({ queryKey: ["admin-active-jobs"] });
          queryClient.invalidateQueries({ queryKey: ["admin-stats"] });
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [queryClient]);
}

// Hook for realtime driver updates (for admin dashboard)
export function useRealtimeDrivers() {
  const queryClient = useQueryClient();

  useEffect(() => {
    const channel = supabase
      .channel("drivers-realtime")
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: "drivers",
        },
        () => {
          queryClient.invalidateQueries({ queryKey: ["admin-drivers"] });
          queryClient.invalidateQueries({ queryKey: ["online-drivers"] });
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [queryClient]);
}
